"""empty message

Revision ID: 9975e4e992b1
Revises: 
Create Date: 2025-12-29 13:53:06.325517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9975e4e992b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jadwal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_kegiatan', sa.String(length=200), nullable=False),
    sa.Column('tanggal_mulai', sa.DateTime(), nullable=False),
    sa.Column('lokasi', sa.String(length=200), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kamar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor_kamar', sa.String(length=50), nullable=False),
    sa.Column('tipe', sa.String(length=50), nullable=True),
    sa.Column('harga', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('kosong', 'terisi'), nullable=True),
    sa.Column('fasilitas', sa.Text(), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomor_kamar')
    )
    op.create_table('peraturan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isi', sa.Text(), nullable=False),
    sa.Column('dibuat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'penghuni'), nullable=False),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('bg_profile_photo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('penghuni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('no_hp', sa.String(length=20), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('jenis_kelamin', sa.Enum('L', 'P'), nullable=True),
    sa.Column('tanggal_masuk', sa.Date(), nullable=False),
    sa.Column('tanggal_keluar', sa.Date(), nullable=True),
    sa.Column('kamar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kamar_id'], ['kamar.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pengumuman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=200), nullable=False),
    sa.Column('isi', sa.Text(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('dibuat_oleh', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dibuat_oleh'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pengaduan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penghuni_id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=150), nullable=False),
    sa.Column('isi', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('menunggu', 'diproses', 'selesai', name='status_pengaduan'), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('tanggapan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['penghuni_id'], ['penghuni.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pengaduan')
    op.drop_table('pengumuman')
    op.drop_table('penghuni')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('peraturan')
    op.drop_table('kamar')
    op.drop_table('jadwal')
    # ### end Alembic commands ###
